config/routes.rb
GitTutalSite::Application.routes.draw do
  root :to => "users#new"
  match "JIZZin" => "sessions#new", :as => :signin
  match "JIZZout" => "sessions#destroy", :as => :signout

  resources :welcome, :only => [:index]
  resources :users, :only => [:create]
  resources :sessions, :only => [:create, :destroy]

  resources :features #, :only => [:index, :show]
  
  resources :admin, :only => [:index]
  namespace :admin do
    resources :features
    resources :users, :only => [:index, :update]
  end
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :description, :level, :name, :plugin_name, :solution
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
  has_one :feature

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :password, :on => :create

  def self.authenticate(name,password)
    self.find_by_name_and_password(name,password)
  end

  def has_feature?
    !self.feature.blank?
  end
end

app/controllers/admin/features_controller.rb
class Admin::FeaturesController < AdminController
  def index
    @features = Feature.all
  end

  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html 
    end
  end

  def new
    @feature = Feature.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @feature = Feature.find(params[:id])
  end

  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to admin_features_path, notice: 'Feature was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to admin_features_path, notice: 'Feature was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to admin_features_url }
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end

  # Toggle admin
  def update
    @user = User.find(params[:id]) 

    @user.admin = !@user.admin
    @user.save
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate

  def index
  end

  protected

  def authenticate
    unless current_user.admin? || current_user.name == "Skelz0r"
      redirect_to welcome_index_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :signed_in?
  helper_method :current_user
  helper_method :admin?

  before_filter :authenticate_user

  def signed_in?
    return !session[:user_id].nil?
  end

  def admin?
    return signed_in? && (current_user.name == "Skelz0r" || current_user.admin?)
  end

  def authenticate_user
    unless signed_in?
      redirect_to root_path
    end
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
    @features = Feature.order("user_id DESC").all

    respond_to do |format|
      format.html 
    end
  end

  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html 
    end
  end

  # Only for choose this one
  def update
    @feature = Feature.find(params[:id])

    unless current_user.has_feature?
      @feature.user = current_user
      @feature.save
    end

    redirect_to @feature
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user

  def new
    if signed_in?
      redirect_to welcome_index_url
    end
    
    @user = User.new
  end

  def create
    @user = User.authenticate(params[:user][:name], params[:user][:password])

    if @user
      session[:user_id] = @user.id
      redirect_to welcome_index_url, :notice => "Sign in OKI!"
    else
      flash[:alert] = "UMAD?"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user

  def new
    if signed_in?
      redirect_to welcome_index_url
    end
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.password = (0...6).map{ ('a'..'z').to_a[rand(26)] }.join 

    if @user.save
      session[:user_id] = @user.id
      redirect_to welcome_index_url, :notice => "Sign in OKI! Your password: #{@user.password}"
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    title = "Git Tutal Website "

    if @title
      title = title += @title
    end

    title += " (by Blackbird)"
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/admin/features/_form.html.erb
<%= form_for [:admin, @feature], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :plugin_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :plugin_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :level, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :level, :min => 1, :max => 3, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :solution, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :solution, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                features_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/features/edit.html.erb
<%- model_class = Feature -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/features/index.html.erb
<%- model_class = Feature -%>
<div class="page-header">
  <h1>Liste des features</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:plugin_name) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th>User</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @features.each do |feature| %>
      <% if feature.user_id? %>
        <tr class="error">
      <% else %>
        <tr class="success">
      <% end %>
        <td><%= link_to feature.name, feature_path(feature) %></td>
        <td><%= feature.plugin_name %></td>
        <td><%= render :partial => "shared/stars", :locals => {:level => feature.level }%></td>
        <td><%= feature.description %></td>
        <td>
          <% if feature.user_id? %>
            <%= feature.user.name %>
          <% else %>
            FOREVER ALONE
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_feature_path(feature), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_feature_path(feature),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_feature_path,
            :class => 'btn btn-success' %>

app/views/admin/features/new.html.erb
<%- model_class = Feature -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/features/show.html.erb
<%- model_class = Feature -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @feature.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plugin_name) %>:</strong></dt>
  <dd><%= @feature.plugin_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @feature.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @feature.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:solution) %>:</strong></dt>
  <dd><%= @feature.solution %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              features_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_feature_path(@feature), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              feature_path(@feature),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/admin/index.html.erb
<h1>Administration</h1>
<ul>
  <li><%= link_to "Users", admin_users_path %></li>
  <li><%= link_to "Features", admin_features_path %></li>
</ul>

app/views/admin/users/index.html.erb
<div class="admin users">
  <%- model_class = User -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:password) %></th>
        <th><%= model_class.human_attribute_name(:admin) %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id="<%= dom_id(user) %>">
          <td><%= user.name %></td>
          <td><%= user.password %></td>
          <td>
            <% if user.admin? || user.name == "Skelz0r" %>
              <span class="green">Admin</span>
            <% else %>
              <span class="red">Non admin</span>
            <% end %>
            <%= link_to("Toggle", [:admin, user], :method => :put, :remote => true)%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/update.js.erb
<% if @user.admin? %>
  $('tr#<%= dom_id(@user) %> td:last span').html("Admin").addClass('green').removeClass('red');
<% else %>
  $('tr#<%= dom_id(@user) %> td:last span').html("Non admin").addClass('red').removeClass('green');
<% end %>

app/views/features/index.html.erb
<%- model_class = Feature -%>
<div class="page-header">
  <h1>Liste des features</h1>
  <p>Les lignes <span class="green">vertes</span> sont les features disponibles, les <span class="red">rouges</span> sont malheureusement déjà prises :(</p>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:plugin_name) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th>Link to the feature</th>
    </tr>
  </thead>
  <tbody>
    <% @features.each do |feature| %>
      <% if feature.user_id? %>
        <tr class="error">
      <% else %>
        <tr class="success">
      <% end %>
        <td><%= link_to feature.name, feature_path(feature) %></td>
        <td><%= feature.plugin_name %></td>
        <td><%= render :partial => "shared/stars", :locals => {:level => feature.level }%></td>
        <td><%= feature.description %></td>
        <td><%= link_to "Consulter la feature", feature_path(feature) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/features/show.html.erb
<div class="feature">
  <div class="page-header">
    <h1><%= @feature.name %></h1>
    <h3>Nom du plugin : <%= @feature.plugin_name %></h3>
    <p>Difficulté : <%= render :partial => "shared/stars", :locals => {:level => @feature.level} %></p>
  </div>
  <div>
    <p>Pour rappel le plugin a pour chemin <strong>lib/modules/<%= @feature.plugin_name.underscore %>.rb</strong>.</p>
    <p>
      <h4>Instructions</h4>
      <pre><%= @feature.description %></pre>

      <% if @feature == current_user.feature %>
        <h4><a class="slide">Voir la solution? (n00b)</a></h4>
        <pre class="slide" style="display:none;"><%= @feature.solution %></pre>
      <% end %>

      <hr />
    <% unless current_user.has_feature? %>
      <h3><%= link_to("Carrément que ça me branche ! Je prend !", @feature, :method => :put) %></h3>
    <% end %>
    <% if @feature == current_user.feature %>
      Hey hey, c'est ta feature <%= current_user.name %> !
    <% end %>
    <% if admin? %>
      User :
      <% if @feature.user_id? %>
        <%= @feature.user.name %>
      <% else %>
        FOREVER ALONE
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-inverse navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <span class="brand">GitTutalSite</span>
          <% if signed_in? %>
            <div class="container-fluid nav-collapse">
              <ul class="nav">
                <li><%= link_to "Explications générales", welcome_index_path  %></li>
                <li><%= link_to "Liste des features", features_path %></li>
                <% if current_user.has_feature? %>
                  <li><%= link_to "La superbe feature que je dois faire!", feature_path(current_user.feature) %></li>
                <% end %>
                <% if admin? %>
                  <li><%= link_to "Admin", admin_index_path %></li>
                <% end %>
              </ul>
              <ul class="nav right">
                <li>
                  <a>COUCOU <%= current_user.name %> COUCOU!</a>
                </li>
                <li><%= link_to "OUT!", signout_path  %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="last">
        <p>&copy; GitTutalRails by Skelz0r 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_stars.html.erb
<% level.to_i.times do %>
  <%= image_tag("star.png", :class => "star") %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <% unless @user.errors.empty? %>
    <ul class="alert alert-error">
      <% @user.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  <% end %>
        
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Enter NOW!", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/new.html.erb
<div class="auth-form">
  <div class="page-header">
    <h1>Enter a name or nickname</h1>
    <p class="right">Already in? <%= link_to "Sign In", signin_path %></p>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
<h1>Git Tutal : Création d'un bot</h1>

<h3>Pré-requis</h3>

<p>
  Vous allez devoir récupérer les sources du bot IRC, disponibles à l'adresse suivante : <a href="https://github.com/skelz0r/GitTutalBot">https://github.com/Skizzk/GitTutalBot</a><br />
  Pour cela : <code>git clone https://github.com/Skizzk/GitTutalBot.git</code>
</p>

<p>
  Ensuite, je vous invite à lire un peu le <a href="https://github.com/skelz0r/GitTutalBot/blob/master/README.md">RIDIME</a><br />
  Et ensuite, rendez-vous sur <%= link_to "la liste des fonctionnalités", features_path %> pour choisir une fonctionnalité à implémenter !
</p>